import type { Metadata } from "next";
import { Outfit } from "next/font/google";

const outfitSans = Outfit({
  variable: "--font-outifit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${outfitSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
